spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/api_financeira
spring.datasource.username=SEU_USER_AQUI
spring.datasource.password=SUA_SENHA_AQUI
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# Segredo para assinar o Token JWT (em producao, isso seria uma variavel de ambiente complexa)
api.security.token.secret=SUA_CHAVE_SECRETA